# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
#
# SPDX-License-Identifier: MIT

name: Reuse Check

on: [push]

jobs:
  reuse:
    name: "reuse"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Test reuse
        uses: reuse-tool/reuse-action@v1.0.0
        with:
          args: check --all --verbose